// ------------------------------------------------------------------------------------------------
export const credential = JSON.parse(
  Buffer.from(
    `eyJjcmVkZW50aWFsIjp7InJhd0lkIjoiSW00ak85akI5aDRoTWZLN2RYd0wrdz09IiwiaWQiOiJJbTRqTzlqQjloNGhNZks3ZFh3TC13IiwidHlwZSI6InB1YmxpYy1rZXkifSwiYXV0aERhdGEiOnsiY3JlZGVudGlhbElkIjoiSW00ak85akI5aDRoTWZLN2RYd0wrdz09IiwicHVibGljS2V5T2JqZWN0IjoicFFFQ0F5WWdBU0ZZSUR5V3R5eDZqVDRnUXdCbjVWNGVzcFB3ZWgwZ1RZY1B6VFEvbVk0OU0rVnBJbGdnQjlkWkJXR3JRbVdqRE1jczdlYWxFbFlrczNlR2ZqNFZJdjhmVmYrcXJHUT0ifSwicmVzcG9uc2UiOnsiYXR0ZXN0YXRpb25PYmplY3QiOiJvMk5tYlhSa2JtOXVaV2RoZEhSVGRHMTBvR2hoZFhSb1JHRjBZVmlVU1pZTjVZZ09qR2gwTkJjUFpIWmdXNC9rcnJtaWhqTEhtVnp6dW9NZGwyTmRBQUFBQU9xYmpXWk5BUjBoUE9TMnRJeTFkZFFBRUNKdUl6dll3ZlllSVRIeXUzVjhDL3VsQVFJREppQUJJVmdnUEphM0xIcU5QaUJEQUdmbFhoNnlrL0I2SFNCTmh3L05ORCtaamowejVXa2lXQ0FIMTFrRllhdENaYU1NeHl6dDVxVVNWaVN6ZDRaK1BoVWkveDlWLzZxc1pBPT0iLCJhdXRoZW50aWNhdG9yRGF0YSI6IlNaWU41WWdPakdoME5CY1BaSFpnVzQva3JybWloakxIbVZ6enVvTWRsMk5kQUFBQUFPcWJqV1pOQVIwaFBPUzJ0SXkxZGRRQUVDSnVJenZZd2ZZZUlUSHl1M1Y4Qy91bEFRSURKaUFCSVZnZ1BKYTNMSHFOUGlCREFHZmxYaDZ5ay9CNkhTQk5ody9OTkQrWmpqMHo1V2tpV0NBSDExa0ZZYXRDWmFNTXh5enQ1cVVTVmlTemQ0WitQaFVpL3g5Vi82cXNaQT09IiwiY2xpZW50RGF0YUpTT05EZWNvZGVkIjoie1widHlwZVwiOlwid2ViYXV0aG4uY3JlYXRlXCIsXCJjaGFsbGVuZ2VcIjpcIlRtUjFTbXByYXpreVJHOWhSWGhqWjFSd1pYcHhNV3hDVFVsVVJqZExUeklcIixcIm9yaWdpblwiOlwiaHR0cHM6Ly9sb2NhbGhvc3Q6MzAwMFwiLFwiY3Jvc3NPcmlnaW5cIjpmYWxzZX0iLCJjbGllbnREYXRhSlNPTiI6ImV5SjBlWEJsSWpvaWQyVmlZWFYwYUc0dVkzSmxZWFJsSWl3aVkyaGhiR3hsYm1kbElqb2lWRzFTTVZOdGNISmhlbXQ1VWtjNWFGSllhR3BhTVZKM1dsaHdlRTFYZUVOVVZXeFZVbXBrVEZSNlNTSXNJbTl5YVdkcGJpSTZJbWgwZEhCek9pOHZiRzlqWVd4b2IzTjBPak13TURBaUxDSmpjbTl6YzA5eWFXZHBiaUk2Wm1Gc2MyVjkiLCJ0cmFuc3BvcnRzIjpbImh5YnJpZCIsImludGVybmFsIl19LCJwdWJsaWNLZXkiOiJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVQSmEzTEhxTlBpQkRBR2ZsWGg2eWsvQjZIU0JOaHcvTk5EK1pqajB6NVdrSDExa0ZZYXRDWmFNTXh5enQ1cVVTVmlTemQ0WitQaFVpL3g5Vi82cXNaQT09IiwicHVibGljS2V5QWxnb3JpdGhtIjotN30=`,
    "base64"
  ).toString()
);

// ------------------------------------------------------------------------------------------------

export const assertion = JSON.parse(
  Buffer.from(
    `eyJpZCI6IkltNGpPOWpCOWg0aE1mSzdkWHdMLXciLCJyYXdJZCI6IkltNGpPOWpCOWg0aE1mSzdkWHdMK3c9PSIsInR5cGUiOiJwdWJsaWMta2V5IiwiYXV0aERhdGEiOnsicnBJZEhhc2giOiJTWllONVlnT2pHaDBOQmNQWkhaZ1c0L2tycm1paGpMSG1Wenp1b01kbDJNPSIsImZsYWdzQnVmIjoiSFE9PSIsImZsYWdzIjp7InVwIjp0cnVlLCJ1diI6dHJ1ZSwiYmUiOnRydWUsImJzIjp0cnVlLCJhdCI6ZmFsc2UsImVkIjpmYWxzZSwiZmxhZ3NJbnQiOjI5fSwiY291bnRlciI6MCwiY291bnRlckJ1ZiI6IkFBQUFBQT09IiwiY3JlZGVudGlhbElkIjoiIiwiY3JlZGVudGlhbFB1YmxpY0tleSI6IiJ9LCJyZXNwb25zZSI6eyJjbGllbnREYXRhSlNPTkRlY29kZWQiOiJ7XCJ0eXBlXCI6XCJ3ZWJhdXRobi5nZXRcIixcImNoYWxsZW5nZVwiOlwiYVRKcmNUTkNRbVl0YUVwNFdXSnhRUzAwU3pKUVl6TnJNRWRmYXpWdGEyd1wiLFwib3JpZ2luXCI6XCJodHRwczovL2xvY2FsaG9zdDozMDAwXCIsXCJjcm9zc09yaWdpblwiOmZhbHNlfSIsImNsaWVudERhdGFKU09OIjoiZXlKMGVYQmxJam9pZDJWaVlYVjBhRzR1WjJWMElpd2lZMmhoYkd4bGJtZGxJam9pWVZSS2NtTlVUa05SYlZsMFlVVndORmRYU25oUlV6QXdVM3BLVVZsNlRuSk5SV1JtWVhwV2RHRXlkeUlzSW05eWFXZHBiaUk2SW1oMGRIQnpPaTh2Ykc5allXeG9iM04wT2pNd01EQWlMQ0pqY205emMwOXlhV2RwYmlJNlptRnNjMlY5IiwiYXV0aGVudGljYXRvckRhdGEiOiJTWllONVlnT2pHaDBOQmNQWkhaZ1c0L2tycm1paGpMSG1Wenp1b01kbDJNZEFBQUFBQT09Iiwic2lnbmF0dXJlIjoiTUVRQ0lCT2ExWjJEQmI1RlZSSDNjWGdOTEpXMkVKdHZTaWZ5WFpDSVFRVURMWXlCQWlBSXJ6Wm9vTDY4Q3REZzZQUmdPSUR6Zi9EQ2U4T2VqVFBSRWZZZ0tOeTBjUT09IiwidXNlckhhbmRsZSI6ZmFsc2V9fQ==`,
    "base64"
  ).toString()
);

// ------------------------------------------------------------------------------------------------
