module.exports = {
  assign: require("./assign.js"),
  base64From: require("./base64From.js"),
  base64To: require("./base64To.js"),
  base64URLEncode: require("./base64URLEncode.js"),
  currencyBRToFloat: require("./currencyBRToFloat"),
  dateToFormat: require("./dateToFormat.js"),
  dateFirstHourOfDay: require("./dateFirstHourOfDay.js"),
  dateLastHourOfDay: require("./dateLastHourOfDay.js"),
  deleteKeys: require("./deleteKeys.js"),
  generateHash: require("./generateHash.js"),
  generateSimpleId: require("./generateSimpleId.js"),
  generateRandomString: require("./generateRandomString.js"),
  getExecutionTime: require("./getExecutionTime.js"),
  JSONFrom: require("./JSONFrom.js"),
  JSONTo: require("./JSONTo.js"),
  normalize: require("./normalize.js"),
  regexDigitsOnly: require("./regexDigitsOnly.js"),
  regexReplaceTrim: require("./regexReplaceTrim.js"),
  regexLettersOnly: require("./regexLettersOnly.js"),
  removeDuplicatedStrings: require("./removeDuplicatedStrings.js"),
  stringToDate: require("./stringToDate.js"),
  stringToDateToFormat: require("./stringToDateToFormat.js"),
  stringToFormat: require("./stringToFormat.js"),
  toString: require("./toString.js"),
};
